// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RolesPB.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace ProtoMsg {

  #region Messages
  public sealed class RolesCreateC2S : pb::IMessage {
    private static readonly pb::MessageParser<RolesCreateC2S> _parser = new pb::MessageParser<RolesCreateC2S>(() => new RolesCreateC2S());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RolesCreateC2S> Parser { get { return _parser; } }

    /// <summary>Field number for the "NickName" field.</summary>
    public const int NickNameFieldNumber = 1;
    private string nickName_ = "";
    /// <summary>
    ///昵称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NickName {
      get { return nickName_; }
      set {
        nickName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NickName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NickName);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NickName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NickName);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            NickName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed class RolesCreateS2C : pb::IMessage {
    private static readonly pb::MessageParser<RolesCreateS2C> _parser = new pb::MessageParser<RolesCreateS2C>(() => new RolesCreateS2C());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RolesCreateS2C> Parser { get { return _parser; } }

    /// <summary>Field number for the "Result" field.</summary>
    public const int ResultFieldNumber = 1;
    private int result_;
    /// <summary>
    ///结果:0创建成功 1角色已存在
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "RolesInfo" field.</summary>
    public const int RolesInfoFieldNumber = 2;
    private global::ProtoMsg.RolesInfo rolesInfo_;
    /// <summary>
    ///角色信息 结果为0时返回
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtoMsg.RolesInfo RolesInfo {
      get { return rolesInfo_; }
      set {
        rolesInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Result);
      }
      if (rolesInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RolesInfo);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
      }
      if (rolesInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RolesInfo);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Result = input.ReadInt32();
            break;
          }
          case 18: {
            if (rolesInfo_ == null) {
              rolesInfo_ = new global::ProtoMsg.RolesInfo();
            }
            input.ReadMessage(rolesInfo_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
